let a = Number(prompt("Enter the first number"));
let b = Number(prompt("Enter the second number"));
let sum = a + b;
let dif = a - b;
let multiply = a * b;
let balance = a / b;
console.log(`Sum: ${sum}`);
console.log(`Difference: ${Math.abs(dif)}`);
console.log(`Multiply: ${multiply}`);
console.log(`Balance: ${balance}`);
